// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "drrobotsdkcontrolctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CDrrobotsdkcontrolctrl1

IMPLEMENT_DYNCREATE(CDrrobotsdkcontrolctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDrrobotsdkcontrolctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CDrrobotsdkcontrolctrl1 operations
