// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vitaminctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CVitaminctrl1

IMPLEMENT_DYNCREATE(CVitaminctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVitaminctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CVitaminctrl1 operations
